DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `LANGWORDS_DELETE`(IN `P_ID` INT, IN `P_LANGID` INT, IN `P_WORD` TEXT CHARSET utf8, IN `P_NOTE` TEXT CHARSET utf8, IN `P_FAMIID` INT, IN `P_LEVEL` INT, IN `P_CORRECT` INT, IN `P_TOTAL` INT)
    MODIFIES SQL DATA
BEGIN
    DELETE FROM LANGWORDS WHERE ID = P_ID;
    DELETE FROM UNITWORDS WHERE WORDID = P_ID;
    DELETE FROM WORDSFAMI WHERE WORDID = P_ID;
    DELETE FROM WORDSPHRASES WHERE WORDID = P_ID;
    SELECT '0' AS result;
END$$
DELIMITER ;