DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `PATTERNS_SPLIT`(IN `P_ID` INT, IN `P_PATTERNS_SPLIT` TEXT CHARSET utf8)
    NO SQL
BEGIN
    DECLARE n INT Default 0;
    DECLARE ptstr TEXT CHARSET utf8;
    simple_loop: LOOP
        SET n = n + 1;
        SET ptstr = SPLIT_STR(P_PATTERNS_SPLIT, ',', n);
        IF ptstr = '' THEN
            LEAVE simple_loop;
        END IF;
        IF n = 1 THEN
            UPDATE PATTERNS SET PATTERN = ptstr WHERE ID = P_ID;
        ELSE
            INSERT INTO PATTERNS (LANGID, PATTERN, NOTE, TAGS) SELECT LANGID, ptstr, NOTE, TAGS FROM PATTERNS WHERE ID = P_ID;
            INSERT INTO PATTERNSWEBPAGES (PATTERNID, SEQNUM, WEBPAGEID) SELECT LAST_INSERT_ID(), SEQNUM, WEBPAGEID FROM PATTERNSWEBPAGES WHERE PATTERNID = P_ID;
        END IF;
    END LOOP simple_loop;
    SELECT '0' AS result;
END$$
DELIMITER ;