DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `UNITPHRASES_DELETE`(IN `P_ID` INT, IN `P_LANGID` INT, IN `P_TEXTBOOKID` INT, IN `P_UNIT` INT, IN `P_PART` INT, IN `P_SEQNUM` INT, IN `P_PHRASEID` INT, IN `P_PHRASE` TEXT CHARSET utf8, IN `P_TRANSLATION` TEXT CHARSET utf8)
    MODIFIES SQL DATA
BEGIN
    DECLARE UPCNT INT;
    DECLARE WPCNT INT;
    DECLARE result TEXT;

    DELETE FROM UNITPHRASES WHERE ID = P_ID;
    SELECT COUNT(*) INTO UPCNT FROM UNITPHRASES WHERE PHRASEID = P_PHRASEID;
    SELECT COUNT(*) INTO WPCNT FROM WORDSPHRASES WHERE PHRASEID = P_PHRASEID;
    IF UPCNT = 0 AND WPCNT = 0 THEN
        -- exclusive
        DELETE FROM LANGPHRASES WHERE ID = P_PHRASEID;
        SET result = '0';
    ELSE
        -- non-exclusive
        SET result = '1';
    END IF;
    SELECT result;
END$$
DELIMITER ;