DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `UNITPHRASES_UPDATE`(IN `P_ID` INT, IN `P_LANGID` INT, IN `P_TEXTBOOKID` INT, IN `P_UNIT` INT, IN `P_PART` INT, IN `P_SEQNUM` INT, IN `P_PHRASEID` INT, IN `P_PHRASE` TEXT CHARSET utf8, IN `P_TRANSLATION` TEXT CHARSET utf8)
    NO SQL
BEGIN
    DECLARE UPOLDCNT INT;
    DECLARE LPOLDPHRASE TEXT CHARSET utf8;
    DECLARE result TEXT;
    DECLARE NEW_PHRASEID INT;
    DECLARE LPNEWCNT INT;

    SELECT COUNT(*) INTO UPOLDCNT FROM UNITPHRASES WHERE PHRASEID = P_PHRASEID;
    IF UPOLDCNT = 0 THEN
        -- non-existing phrase
        SET result = '0';
    ELSE
        SET NEW_PHRASEID = P_PHRASEID;
        SELECT PHRASE INTO LPOLDPHRASE FROM LANGPHRASES WHERE ID = P_PHRASEID;
        IF CAST(LPOLDPHRASE AS CHAR CHARSET BINARY) = CAST(P_PHRASE AS CHAR CHARSET BINARY) THEN
            -- phrase intact
            UPDATE LANGPHRASES SET TRANSLATION = P_TRANSLATION WHERE ID = P_PHRASEID;
            SET result = '1';
        ELSE
            -- phrase changed
            SELECT COUNT(*) INTO LPNEWCNT FROM LANGPHRASES WHERE LANGID = P_LANGID AND CAST(PHRASE AS CHAR CHARSET BINARY) = CAST(P_PHRASE AS CHAR CHARSET BINARY);
            IF UPOLDCNT = 1 THEN
                /* exclusive */
                IF LPNEWCNT = 0 THEN
                    -- new phrase
                    UPDATE LANGPHRASES SET PHRASE = P_PHRASE, TRANSLATION = P_TRANSLATION WHERE ID = P_PHRASEID;
                    SET result = '2';
                ELSE
                    -- existing phrase
                    DELETE FROM LANGPHRASES WHERE ID = P_PHRASEID;
                    SELECT ID INTO NEW_PHRASEID FROM LANGPHRASES WHERE LANGID = P_LANGID AND CAST(PHRASE AS CHAR CHARSET BINARY) = CAST(P_PHRASE AS CHAR CHARSET BINARY) LIMIT 1;
                    SET result = '3';
                END IF;
            ELSE
                -- non-exclusive
                IF LPNEWCNT = 0 THEN
                    /* new phrase */
                    INSERT LANGPHRASES (LANGID, PHRASE, TRANSLATION) VALUES (P_LANGID, P_PHRASE, P_TRANSLATION);
                    SELECT LAST_INSERT_ID() INTO NEW_PHRASEID;
                    SET result = '4';
                ELSE
                    -- existing phrase
                    SELECT ID INTO NEW_PHRASEID FROM LANGPHRASES WHERE LANGID = P_LANGID AND CAST(PHRASE AS CHAR CHARSET BINARY) = CAST(P_PHRASE AS CHAR CHARSET BINARY) LIMIT 1;
                    SET result = '5';
                END IF;
            END IF;
        END IF;
        UPDATE UNITPHRASES SET UNIT = P_UNIT, PART = P_PART, SEQNUM = P_SEQNUM, PHRASEID = NEW_PHRASEID WHERE ID = P_ID;
        UPDATE WORDSPHRASES SET PHRASEID = NEW_PHRASEID WHERE PHRASEID = P_PHRASEID;
        UPDATE PATTERNSPHRASES SET PHRASEID = NEW_PHRASEID WHERE PHRASEID = P_PHRASEID;
    END IF;
    SELECT result;
END$$
DELIMITER ;