DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `UNITWORDS_CREATE`(IN `P_ID` INT, IN `P_LANGID` INT, IN `P_TEXTBOOKID` INT, IN `P_UNIT` INT, IN `P_PART` INT, IN `P_SEQNUM` INT, IN `P_WORDID` INT, IN `P_WORD` TEXT CHARSET utf8, IN `P_NOTE` TEXT CHARSET utf8, IN `P_FAMIID` INT, IN `P_LEVEL` INT, IN `P_CORRECT` INT, IN `P_TOTAL` INT)
    MODIFIES SQL DATA
BEGIN
    DECLARE result TEXT;
    DECLARE LWCNT INT;
    DECLARE NEW_WORDID INT;

    SELECT COUNT(*) INTO LWCNT FROM LANGWORDS WHERE LANGID = P_LANGID AND CAST(WORD AS CHAR CHARSET BINARY) = CAST(P_WORD AS CHAR CHARSET BINARY);
    IF LWCNT = 0 THEN
        -- new word
        INSERT LANGWORDS (LANGID, WORD, NOTE) VALUES (P_LANGID, P_WORD, P_NOTE);
        SELECT LAST_INSERT_ID() INTO NEW_WORDID;
        SET result = '0';
    ELSE
        -- existing word
        SELECT ID INTO NEW_WORDID FROM LANGWORDS WHERE LANGID = P_LANGID AND CAST(WORD AS CHAR CHARSET BINARY) = CAST(P_WORD AS CHAR CHARSET BINARY) LIMIT 1;
        SET result = '1';
    END IF;
    INSERT UNITWORDS (TEXTBOOKID, UNIT, PART, SEQNUM, WORDID) VALUES (P_TEXTBOOKID, P_UNIT, P_PART, P_SEQNUM, NEW_WORDID);
    SELECT LAST_INSERT_ID() AS NEW_ID, result;
END$$
DELIMITER ;